baseURL: https://heartfelt-mandazi-b13d7f.netlify.app
languageCode: zh-cn
defaultContentLanguage: zh
title: "Cary's Blog"
theme: "archie"
copyright: "Cary"
enableEmoji: true
hasCJKLanguage: true

pagination:
  pagerSize: 12

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  highlight:
    style: emacs
    codeFences: true
    guessSyntax: true

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

params:
  mode: toggle
  useCDN: false
  subtitle: "随便写写"
  description: "Cary's personal website"
  favicon: /images/favicon-32x32.png
  mainSections:
    - thoughts
    - tech
    - photography
    - fitness
  excludedTypes:
    - page
  customCSS:
    - css/archie-custom.css
  gitRepo: https://github.com/cary-xgl/blog
  gitBranch: main
  utterances:
    enable: false
    repo: cary-xgl/blog
    issueTerm: pathname
    label: Comment
    theme: github-light

menu:
  main:
    - name: 首页
      url: /
      weight: 1
    - name: 随想
      url: /thoughts/
      weight: 2
    - name: 技术
      url: /tech/
      weight: 3
    - name: 摄影
      url: /photography/
      weight: 4
    - name: 健身
      url: /fitness/
      weight: 5
    - name: 标签
      url: /tags/
      weight: 6
    - name: 搜索
      url: /search/
      weight: 7
